import type { FieldDefinition } from '../types/fields'

export type { FieldDefinition }

export const FIELD_DEFINITIONS: FieldDefinition[] = [
  {
    id: 'model_display_name',
    label: 'Model',
    description: 'Current model display name (e.g., "Opus", "Sonnet")',
    jqPath: '.model.display_name',
    exampleValue: 'Sonnet',
    category: 'model',
  },
  {
    id: 'model_id',
    label: 'Model ID',
    description: 'Full model identifier string',
    jqPath: '.model.id',
    exampleValue: 'claude-sonnet-4-6',
    category: 'model',
  },
  {
    id: 'context_used_pct',
    label: 'Context %',
    description: 'Percentage of context window used',
    jqPath: '.context_window.used_percentage // 0',
    exampleValue: '42',
    category: 'context',
  },
  {
    id: 'context_remaining_pct',
    label: 'Context Remaining',
    description: 'Percentage of context window remaining',
    jqPath: '.context_window.remaining_percentage // 0',
    exampleValue: '58',
    category: 'context',
  },
  {
    id: 'context_window_size',
    label: 'Context Size',
    description: 'Maximum context window size in tokens',
    jqPath: '.context_window.context_window_size',
    exampleValue: '200000',
    category: 'context',
  },
  {
    id: 'context_total_input_tokens',
    label: 'Input Tokens',
    description: 'Cumulative input tokens used this session',
    jqPath: '.context_window.total_input_tokens',
    exampleValue: '15234',
    category: 'context',
  },
  {
    id: 'context_total_output_tokens',
    label: 'Output Tokens',
    description: 'Cumulative output tokens generated this session',
    jqPath: '.context_window.total_output_tokens',
    exampleValue: '4521',
    category: 'context',
  },
  {
    id: 'cost_total_usd',
    label: 'Cost (USD)',
    description: 'Total session cost in US dollars',
    jqPath: '.cost.total_cost_usd',
    exampleValue: '0.0123',
    category: 'cost',
  },
  {
    id: 'cost_duration_ms',
    label: 'Duration',
    description: 'Total wall-clock time since session started (milliseconds)',
    jqPath: '.cost.total_duration_ms',
    exampleValue: '45000',
    category: 'cost',
  },
  {
    id: 'cost_lines_added',
    label: 'Lines Added',
    description: 'Lines of code added this session',
    jqPath: '.cost.total_lines_added',
    exampleValue: '156',
    category: 'cost',
  },
  {
    id: 'cost_lines_removed',
    label: 'Lines Removed',
    description: 'Lines of code removed this session',
    jqPath: '.cost.total_lines_removed',
    exampleValue: '23',
    category: 'cost',
  },
  {
    id: 'workspace_current_dir',
    label: 'Working Dir',
    description: 'Current working directory path',
    jqPath: '.workspace.current_dir',
    exampleValue: '/home/user/my-project',
    category: 'workspace',
  },
  {
    id: 'workspace_project_dir',
    label: 'Project Dir',
    description: 'Directory where Claude Code was launched',
    jqPath: '.workspace.project_dir',
    exampleValue: '/home/user/my-project',
    category: 'workspace',
  },
  {
    id: 'version',
    label: 'CC Version',
    description: 'Claude Code version string',
    jqPath: '.version',
    exampleValue: '1.0.80',
    category: 'session',
  },
  {
    id: 'session_id',
    label: 'Session ID',
    description: 'Unique session identifier',
    jqPath: '.session_id',
    exampleValue: 'abc123def456',
    category: 'session',
  },
  {
    id: 'output_style',
    label: 'Output Style',
    description: 'Current output style name',
    jqPath: '.output_style.name',
    exampleValue: 'default',
    category: 'session',
  },
  {
    id: 'vim_mode',
    label: 'Vim Mode',
    description: 'Current vim mode (NORMAL or INSERT) — only present when vim mode is enabled',
    jqPath: '.vim.mode',
    exampleValue: 'NORMAL',
    category: 'advanced',
    conditional: true,
  },
  {
    id: 'agent_name',
    label: 'Agent',
    description: 'Agent name — only present when running with --agent flag',
    jqPath: '.agent.name',
    exampleValue: 'security-reviewer',
    category: 'advanced',
    conditional: true,
  },
  {
    id: 'worktree_name',
    label: 'Worktree',
    description: 'Active worktree name — only present during --worktree sessions',
    jqPath: '.worktree.name',
    exampleValue: 'my-feature',
    category: 'advanced',
    conditional: true,
  },
  {
    id: 'worktree_branch',
    label: 'Worktree Branch',
    description: 'Git branch for the active worktree',
    jqPath: '.worktree.branch',
    exampleValue: 'worktree-my-feature',
    category: 'advanced',
    conditional: true,
  },
  {
    id: 'exceeds_200k',
    label: 'Exceeds 200k',
    description: 'Whether combined token count from last response exceeds 200k',
    jqPath: '.exceeds_200k_tokens',
    exampleValue: 'false',
    category: 'advanced',
  },
]
