import type { FieldDefinition } from '../types/fields'

export const SEPARATOR_PRESETS = [
  { id: 'pipe',  label: 'Pipe',  value: ' | ' },
  { id: 'dash',  label: 'Dash',  value: ' - ' },
  { id: 'dot',   label: 'Dot',   value: ' · ' },
  { id: 'space', label: 'Space', value: '   ' },
  { id: 'slash', label: 'Slash', value: ' / ' },
] as const

export function generatePreview(
  fields: FieldDefinition[],
  enabledIds: string[],
  separator: string,
): string {
  if (enabledIds.length === 0) return ''
  const fieldMap = new Map(fields.map(f => [f.id, f]))
  return enabledIds
    .flatMap(id => {
      const val = fieldMap.get(id)?.exampleValue
      return val !== undefined ? [val] : []
    })
    .join(separator)
}

export function generateScript(
  fields: FieldDefinition[],
  enabledIds: string[],
  separator: string,
): string {
  const fieldMap = new Map(fields.map(f => [f.id, f]))
  const enabledFields = enabledIds
    .map(id => fieldMap.get(id))
    .filter((f): f is FieldDefinition => f !== undefined)

  const extractionLines = enabledFields
    .map(f => `  local ${f.id}\n  ${f.id}=$(jq -r '${f.jqPath}' "$_json")`)
    .join('\n')

  const assembleLines = enabledFields
    .map(f => `  [[ -n "$${f.id}" ]] && _parts+=("$${f.id}")`)
    .join('\n')

  // Use single-quoted bash string — safe for all preset separators
  const sepLiteral = `'${separator}'`

  return `#!/usr/bin/env bash
# Claude Code Statusline
# Generated by https://statusline.tools — edit manually or regenerate online

claude_statusline() {
  local _json="\${HOME}/.claude/statusline.json"
  [[ ! -f "$_json" ]] && return

  # --- field extraction ---
${extractionLines}
  # --- assemble parts ---
  local _parts=()
${assembleLines}
  # --- join and print ---
  local _sep=${sepLiteral}
  local _out=""
  for _part in "\${_parts[@]}"; do
    [[ -n "$_out" ]] && _out+="$_sep"
    _out+="$_part"
  done
  echo "$_out"
}
`
}
